### ISSUE TITLE
failed to get redirect response TypeError: fetch failed

### ISSUE THREAD

**Issue by 0smboy** [mckaywrigley/chatbot-ui#1053]
after i login chatbot ui, i meet:
<img width="1040" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/91452062/c5a93116-77ae-46a5-9c20-ce2a968ffacf">

**Comment by wrapss** [comment]
same here

**Comment by Woldeer** [comment]
@0smboy Did you find a solution to this?

**Comment by wrapss** [comment]
> @0smboy Did you find a solution to this?

this error means that the user does not exist, try clearing your cookies and creating a new user

**Comment by aalev** [comment]
hello, same issue there:

- Azure VM, Ubuntu 22.04, Node v20.11.0
- Signed up a user in chatbot (it appears in profile table)
- When logging in, I get this error: "Error: TypeError: Failed to fetch" in "db/profile.ts (12:10) @ getProfileByUserId"
- So it's user related. in db/profile.ts the previous statement is:
  const { data: profile, error } = await supabase
    .from("profiles")
    .select("*")
    .eq("user_id", userId)
    .single()
- I patched db/profile.ts Error message to display the userId. It's 71ddc30f-c57d-4e9a-95c9-fad9f5809c37, which is in the database.
- So for unknown reason, the await supabase.from("profiles") gets a null object

Any idea ?

**Comment by aalev** [comment]
thanks to @0smboy, finally **solved** by opening enabling traffic to supabase ports on the VM.

**Comment by im-calvin** [comment]
@aalev can you explain how you solved the issue? I'm running into the same thing

**Comment by im-calvin** [comment]
I've been debugging for a bit, I think the issue might have to do with CORS? Specifically, I'm seeing that `The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:54321/rest/v1/profiles?select=*&user_id=eq.6a74af3a-4c0f-43dd-9471-e61d3b09a26d` in the console.

I'm also getting a valid `user_id` (and I can see it in the database table GUI), but the profile is null.

**Comment by im-calvin** [comment]
I fixed the problem, I think what happened for me is that I had a profile that I was auto-logging into that wasn't configured properly. I had to clear the browser cookies and then remake another user and then it worked.

**Comment by inzomiac** [comment]
I've encountered this kind of error and the only solution is to clear the session. Since during url access the workstation or chat id still exists and tries to access it. Though, the authentication session was already closed but the session data still exists.
